"""add_roles_and_relations

Revision ID: 1b139939a729
Revises: 5058fcea8231
Create Date: 2025-12-12 09:33:51.472594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b139939a729'
down_revision: Union[str, None] = '5058fcea8231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.String(), nullable=False, comment='角色ID'),
    sa.Column('tenant_id', sa.String(), nullable=False, comment='租户ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='角色名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='角色描述'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态：True-启用，False-停用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.String(), nullable=True, comment='创建人ID'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_tenant_role_name')
    )
    op.create_index('idx_role_name', 'roles', ['name'], unique=False)
    op.create_index('idx_role_tenant', 'roles', ['tenant_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(), nullable=False, comment='角色ID'),
    sa.Column('permission_id', sa.String(), nullable=False, comment='权限ID'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_index('idx_role_permission_permission', 'role_permissions', ['permission_id'], unique=False)
    op.create_index('idx_role_permission_role', 'role_permissions', ['role_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.String(), nullable=False, comment='角色ID'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_index('idx_user_role_role', 'user_roles', ['role_id'], unique=False)
    op.create_index('idx_user_role_user', 'user_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_user_role_user', table_name='user_roles')
    op.drop_index('idx_user_role_role', table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index('idx_role_permission_role', table_name='role_permissions')
    op.drop_index('idx_role_permission_permission', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('idx_role_tenant', table_name='roles')
    op.drop_index('idx_role_name', table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###

