"""add_permissions_table

Revision ID: 5058fcea8231
Revises: f6709dc3d64d
Create Date: 2025-12-12 09:21:31.295719

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5058fcea8231'
down_revision: Union[str, None] = 'f6709dc3d64d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.String(), nullable=False, comment='权限ID'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='权限码（module:resource:action格式）'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='权限名称'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='权限描述'),
    sa.Column('type', sa.String(length=20), nullable=False, comment='权限类型：menu-菜单，api-接口，button-按钮，tab-Tab页'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='所属模块'),
    sa.Column('tenant_id', sa.String(), nullable=True, comment='租户ID（为空表示系统级权限）'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态：True-启用，False-停用'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.String(), nullable=True, comment='创建人ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_permission_code', 'permissions', ['code'], unique=False)
    op.create_index('idx_permission_module', 'permissions', ['module'], unique=False)
    op.create_index('idx_permission_tenant', 'permissions', ['tenant_id'], unique=False)
    op.create_index('idx_permission_type', 'permissions', ['type'], unique=False)
    op.create_index('idx_phone', 'users', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_phone', table_name='users')
    op.drop_index('idx_permission_type', table_name='permissions')
    op.drop_index('idx_permission_tenant', table_name='permissions')
    op.drop_index('idx_permission_module', table_name='permissions')
    op.drop_index('idx_permission_code', table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###

