"""init

Revision ID: e02162d48751
Revises: 
Create Date: 2025-12-11 16:13:49.719972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e02162d48751'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False, comment='租户ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='租户名称'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='状态：True-启用，False-停用'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='描述'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.String(), nullable=True, comment='创建人ID'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False, comment='用户ID'),
    sa.Column('tenant_id', sa.String(), nullable=False, comment='租户ID'),
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='状态：active-启用，frozen-冻结'),
    sa.Column('is_tenant_admin', sa.Boolean(), nullable=False, comment='是否为租户管理员'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('created_by', sa.String(), nullable=True, comment='创建人ID'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'username', name='uq_tenant_username')
    )
    op.create_index('idx_tenant_id', 'users', ['tenant_id'], unique=False)
    op.create_index('idx_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_username', table_name='users')
    op.drop_index('idx_tenant_id', table_name='users')
    op.drop_table('users')
    op.drop_table('tenants')
    # ### end Alembic commands ###

