"""add tenant code field

Revision ID: e17f03d0744c
Revises: e02162d48751
Create Date: 2025-12-11 16:18:46.919867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17f03d0744c'
down_revision: Union[str, None] = 'e02162d48751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite 需要使用 batch 模式来添加约束
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=50), nullable=False, server_default='', comment='租户编码'))
        batch_op.create_unique_constraint('uq_tenants_code', ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tenants_code', type_='unique')
        batch_op.drop_column('code')
    # ### end Alembic commands ###

